<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datos\3.Datos.csproj" />
    <ProjectReference Include="..\Servicio\4.Servicio.csproj" />
  </ItemGroup>

</Project>
